### ISSUE TITLE
sprockets-traceur not compatible with sprockets 3 betas

### ISSUE THREAD

**Issue by adammw** [gunpowderlabs/sprockets-traceur#2]
```
/Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sprockets-traceur-0.0.1/lib/sprockets/traceur.rb:7:in `<module:Traceur>': uninitialized constant Sprockets::Traceur::Tilt (NameError)
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sprockets-traceur-0.0.1/lib/sprockets/traceur.rb:6:in `<module:Sprockets>'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sprockets-traceur-0.0.1/lib/sprockets/traceur.rb:5:in `<top (required)>'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sprockets-traceur-0.0.1/lib/sprockets-traceur.rb:1:in `require'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sprockets-traceur-0.0.1/lib/sprockets-traceur.rb:1:in `<top (required)>'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `require'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `each'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `each'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `require'
	from /Users/adam/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/bundler-1.7.10/lib/bundler.rb:134:in `require'
```

At a minimum, the gemspec should be updated to not allow Sprockets 3.

**Comment by psyho** [comment]
Closing the issue, since the gemspec defines the dependency on sprockets as `~> 2`.
